---
admin_user_accounts:
  - name: ansible
    ssh_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHwnoWpr6gVMKXbuV7F0MfvN/bsd1fV9cdNIKL+gaTVc
        ansible@r4reach
  - name: vanatta
    ssh_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIENZoW92mNwtkry/yDGSQB51Ap7Jo2wsVON1l5Sk7nJt
        dan@desk
admin_user_deploy_account:
  name: deploy
  ssh_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMfW8x4LuRkk63lgh5NdxGZFKtuxhHiZVh0/T8RfPUlL
    deploy@r4reach
